[package]
name = "flb-plugin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flb-plugin-sys = { path = "../flb-plugin-sys" }
